# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sebastien/Bayer/ScriptsSEB/scripts/GUI/testERIC/includes/EBimage.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GUI_EBimage(object):
    def setupUi(self, GUI_EBimage):
        GUI_EBimage.setObjectName("GUI_EBimage")
        GUI_EBimage.setWindowModality(QtCore.Qt.WindowModal)
        GUI_EBimage.resize(744, 950)
        GUI_EBimage.setMaximumSize(QtCore.QSize(1000, 950))
        GUI_EBimage.setFocusPolicy(QtCore.Qt.StrongFocus)
        GUI_EBimage.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(GUI_EBimage)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcomeFrame = QtWidgets.QFrame(self.centralwidget)
        self.welcomeFrame.setMaximumSize(QtCore.QSize(928, 70))
        self.welcomeFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.welcomeFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.welcomeFrame.setObjectName("welcomeFrame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.welcomeFrame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.writeLabel = QtWidgets.QLabel(self.welcomeFrame)
        self.writeLabel.setObjectName("writeLabel")
        self.gridLayout_7.addWidget(self.writeLabel, 1, 0, 1, 1)
        self.welcomeLabel = QtWidgets.QLabel(self.welcomeFrame)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.gridLayout_7.addWidget(self.welcomeLabel, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.welcomeFrame)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(119, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tabCalibration = QtWidgets.QWidget()
        self.tabCalibration.setObjectName("tabCalibration")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabCalibration)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tabCalibration)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.resetCalibrationPushButton = QtWidgets.QPushButton(self.frame_3)
        self.resetCalibrationPushButton.setMinimumSize(QtCore.QSize(0, 27))
        self.resetCalibrationPushButton.setMaximumSize(QtCore.QSize(700, 27))
        self.resetCalibrationPushButton.setObjectName("resetCalibrationPushButton")
        self.gridLayout_17.addWidget(self.resetCalibrationPushButton, 1, 0, 1, 1)
        self.runCalibrationPushButton = QtWidgets.QPushButton(self.frame_3)
        self.runCalibrationPushButton.setMinimumSize(QtCore.QSize(0, 27))
        self.runCalibrationPushButton.setMaximumSize(QtCore.QSize(700, 27))
        self.runCalibrationPushButton.setObjectName("runCalibrationPushButton")
        self.gridLayout_17.addWidget(self.runCalibrationPushButton, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 1)
        self.setInFrame = QtWidgets.QFrame(self.tabCalibration)
        self.setInFrame.setMaximumSize(QtCore.QSize(16777215, 270))
        self.setInFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.setInFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.setInFrame.setObjectName("setInFrame")
        self.formLayout = QtWidgets.QFormLayout(self.setInFrame)
        self.formLayout.setObjectName("formLayout")
        self.inputSetLabel = QtWidgets.QLabel(self.setInFrame)
        self.inputSetLabel.setMaximumSize(QtCore.QSize(16777215, 34))
        self.inputSetLabel.setObjectName("inputSetLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.inputSetLabel)
        self.inFrame = QtWidgets.QFrame(self.setInFrame)
        self.inFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inFrame.setObjectName("inFrame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.inFrame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.loadSymptomPushButton = QtWidgets.QPushButton(self.inFrame)
        self.loadSymptomPushButton.setMinimumSize(QtCore.QSize(119, 27))
        self.loadSymptomPushButton.setMaximumSize(QtCore.QSize(119, 27))
        self.loadSymptomPushButton.setObjectName("loadSymptomPushButton")
        self.gridLayout_6.addWidget(self.loadSymptomPushButton, 1, 1, 1, 1)
        self.loadLeafPushButton = QtWidgets.QPushButton(self.inFrame)
        self.loadLeafPushButton.setMinimumSize(QtCore.QSize(119, 27))
        self.loadLeafPushButton.setMaximumSize(QtCore.QSize(119, 27))
        self.loadLeafPushButton.setObjectName("loadLeafPushButton")
        self.gridLayout_6.addWidget(self.loadLeafPushButton, 0, 1, 1, 1)
        self.symptomLabel = QtWidgets.QLabel(self.inFrame)
        self.symptomLabel.setMinimumSize(QtCore.QSize(150, 27))
        self.symptomLabel.setMaximumSize(QtCore.QSize(210, 27))
        self.symptomLabel.setObjectName("symptomLabel")
        self.gridLayout_6.addWidget(self.symptomLabel, 1, 0, 1, 1)
        self.symptomOpenLineEdit = QtWidgets.QLineEdit(self.inFrame)
        self.symptomOpenLineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.symptomOpenLineEdit.setMaximumSize(QtCore.QSize(500, 27))
        self.symptomOpenLineEdit.setText("")
        self.symptomOpenLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.symptomOpenLineEdit.setObjectName("symptomOpenLineEdit")
        self.gridLayout_6.addWidget(self.symptomOpenLineEdit, 1, 2, 1, 1)
        self.leafOpenLineEdit = QtWidgets.QLineEdit(self.inFrame)
        self.leafOpenLineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.leafOpenLineEdit.setMaximumSize(QtCore.QSize(500, 27))
        self.leafOpenLineEdit.setText("")
        self.leafOpenLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.leafOpenLineEdit.setObjectName("leafOpenLineEdit")
        self.gridLayout_6.addWidget(self.leafOpenLineEdit, 0, 2, 1, 1)
        self.leafLabel = QtWidgets.QLabel(self.inFrame)
        self.leafLabel.setMinimumSize(QtCore.QSize(150, 27))
        self.leafLabel.setMaximumSize(QtCore.QSize(210, 27))
        self.leafLabel.setObjectName("leafLabel")
        self.gridLayout_6.addWidget(self.leafLabel, 0, 0, 1, 1)
        self.backgroundLabel = QtWidgets.QLabel(self.inFrame)
        self.backgroundLabel.setMinimumSize(QtCore.QSize(150, 27))
        self.backgroundLabel.setMaximumSize(QtCore.QSize(210, 27))
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.gridLayout_6.addWidget(self.backgroundLabel, 2, 0, 1, 1)
        self.loadBackgroundPushButton = QtWidgets.QPushButton(self.inFrame)
        self.loadBackgroundPushButton.setMinimumSize(QtCore.QSize(119, 27))
        self.loadBackgroundPushButton.setMaximumSize(QtCore.QSize(119, 27))
        self.loadBackgroundPushButton.setObjectName("loadBackgroundPushButton")
        self.gridLayout_6.addWidget(self.loadBackgroundPushButton, 2, 1, 1, 1)
        self.backgroundOpenLineEdit = QtWidgets.QLineEdit(self.inFrame)
        self.backgroundOpenLineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.backgroundOpenLineEdit.setMaximumSize(QtCore.QSize(500, 27))
        self.backgroundOpenLineEdit.setText("")
        self.backgroundOpenLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.backgroundOpenLineEdit.setObjectName("backgroundOpenLineEdit")
        self.gridLayout_6.addWidget(self.backgroundOpenLineEdit, 2, 2, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.inFrame)
        self.cat1Frame = QtWidgets.QFrame(self.setInFrame)
        self.cat1Frame.setEnabled(True)
        self.cat1Frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.cat1Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cat1Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cat1Frame.setObjectName("cat1Frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.cat1Frame)
        self.gridLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.category1LabelLineEdit = QtWidgets.QLineEdit(self.cat1Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category1LabelLineEdit.sizePolicy().hasHeightForWidth())
        self.category1LabelLineEdit.setSizePolicy(sizePolicy)
        self.category1LabelLineEdit.setMinimumSize(QtCore.QSize(150, 27))
        self.category1LabelLineEdit.setMaximumSize(QtCore.QSize(210, 27))
        self.category1LabelLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.category1LabelLineEdit.setObjectName("category1LabelLineEdit")
        self.gridLayout_8.addWidget(self.category1LabelLineEdit, 1, 0, 1, 1)
        self.category1OpenLineEdit = QtWidgets.QLineEdit(self.cat1Frame)
        self.category1OpenLineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.category1OpenLineEdit.setMaximumSize(QtCore.QSize(500, 27))
        self.category1OpenLineEdit.setText("")
        self.category1OpenLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.category1OpenLineEdit.setObjectName("category1OpenLineEdit")
        self.gridLayout_8.addWidget(self.category1OpenLineEdit, 1, 2, 1, 1)
        self.loadCategory1PushButton = QtWidgets.QPushButton(self.cat1Frame)
        self.loadCategory1PushButton.setMinimumSize(QtCore.QSize(119, 27))
        self.loadCategory1PushButton.setMaximumSize(QtCore.QSize(119, 27))
        self.loadCategory1PushButton.setObjectName("loadCategory1PushButton")
        self.gridLayout_8.addWidget(self.loadCategory1PushButton, 1, 1, 1, 1)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.cat1Frame)
        self.cat2Frame = QtWidgets.QFrame(self.setInFrame)
        self.cat2Frame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.cat2Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.cat2Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cat2Frame.setObjectName("cat2Frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.cat2Frame)
        self.gridLayout_9.setContentsMargins(9, 0, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.loadCategoryPushButton = QtWidgets.QPushButton(self.cat2Frame)
        self.loadCategoryPushButton.setMinimumSize(QtCore.QSize(119, 27))
        self.loadCategoryPushButton.setMaximumSize(QtCore.QSize(119, 27))
        self.loadCategoryPushButton.setObjectName("loadCategoryPushButton")
        self.gridLayout_9.addWidget(self.loadCategoryPushButton, 0, 1, 1, 1)
        self.category2LabelLineEdit = QtWidgets.QLineEdit(self.cat2Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.category2LabelLineEdit.sizePolicy().hasHeightForWidth())
        self.category2LabelLineEdit.setSizePolicy(sizePolicy)
        self.category2LabelLineEdit.setMinimumSize(QtCore.QSize(150, 27))
        self.category2LabelLineEdit.setMaximumSize(QtCore.QSize(210, 27))
        self.category2LabelLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.category2LabelLineEdit.setObjectName("category2LabelLineEdit")
        self.gridLayout_9.addWidget(self.category2LabelLineEdit, 0, 0, 1, 1)
        self.category2OpenLineEdit = QtWidgets.QLineEdit(self.cat2Frame)
        self.category2OpenLineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.category2OpenLineEdit.setMaximumSize(QtCore.QSize(500, 27))
        self.category2OpenLineEdit.setText("")
        self.category2OpenLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.category2OpenLineEdit.setObjectName("category2OpenLineEdit")
        self.gridLayout_9.addWidget(self.category2OpenLineEdit, 0, 2, 1, 1)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.cat2Frame)
        self.futherFrame = QtWidgets.QFrame(self.setInFrame)
        self.futherFrame.setEnabled(True)
        self.futherFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.futherFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.futherFrame.setObjectName("futherFrame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.futherFrame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.futherCatLabel = QtWidgets.QLabel(self.futherFrame)
        self.futherCatLabel.setMinimumSize(QtCore.QSize(150, 27))
        self.futherCatLabel.setMaximumSize(QtCore.QSize(210, 27))
        self.futherCatLabel.setObjectName("futherCatLabel")
        self.gridLayout_10.addWidget(self.futherCatLabel, 0, 0, 1, 1)
        self.futherCategoriesComboBox = QtWidgets.QComboBox(self.futherFrame)
        self.futherCategoriesComboBox.setMinimumSize(QtCore.QSize(0, 27))
        self.futherCategoriesComboBox.setMaximumSize(QtCore.QSize(60, 25))
        self.futherCategoriesComboBox.setEditable(False)
        self.futherCategoriesComboBox.setMaxCount(10)
        self.futherCategoriesComboBox.setObjectName("futherCategoriesComboBox")
        self.futherCategoriesComboBox.addItem("")
        self.futherCategoriesComboBox.addItem("")
        self.futherCategoriesComboBox.addItem("")
        self.gridLayout_10.addWidget(self.futherCategoriesComboBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 2, 1, 1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.futherFrame)
        self.gridLayout_4.addWidget(self.setInFrame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabCalibration, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.CalibrationOutFrame = QtWidgets.QFrame(self.tab)
        self.CalibrationOutFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CalibrationOutFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CalibrationOutFrame.setObjectName("CalibrationOutFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CalibrationOutFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imgLabel = QtWidgets.QLabel(self.CalibrationOutFrame)
        self.imgLabel.setMinimumSize(QtCore.QSize(480, 480))
        self.imgLabel.setMaximumSize(QtCore.QSize(480, 480))
        self.imgLabel.setText("")
        self.imgLabel.setTextFormat(QtCore.Qt.AutoText)
        self.imgLabel.setScaledContents(True)
        self.imgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imgLabel.setWordWrap(False)
        self.imgLabel.setIndent(0)
        self.imgLabel.setObjectName("imgLabel")
        self.verticalLayout_2.addWidget(self.imgLabel)
        self.frame_2 = QtWidgets.QFrame(self.CalibrationOutFrame)
        self.frame_2.setMaximumSize(QtCore.QSize(999999, 99999))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.viewLayout = QtWidgets.QGridLayout()
        self.viewLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.viewLayout.setObjectName("viewLayout")
        self.gridLayout_3.addLayout(self.viewLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.CalibrationOutFrame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tabAnalysis = QtWidgets.QWidget()
        self.tabAnalysis.setObjectName("tabAnalysis")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabAnalysis)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame = QtWidgets.QFrame(self.tabAnalysis)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.analysisLabel = QtWidgets.QLabel(self.frame)
        self.analysisLabel.setMinimumSize(QtCore.QSize(150, 27))
        self.analysisLabel.setMaximumSize(QtCore.QSize(210, 27))
        self.analysisLabel.setObjectName("analysisLabel")
        self.gridLayout_2.addWidget(self.analysisLabel, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.leafSizeLabel = QtWidgets.QLabel(self.frame_5)
        self.leafSizeLabel.setMinimumSize(QtCore.QSize(120, 27))
        self.leafSizeLabel.setMaximumSize(QtCore.QSize(120, 27))
        self.leafSizeLabel.setObjectName("leafSizeLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.leafSizeLabel)
        self.leafBorderSizeLabel = QtWidgets.QLabel(self.frame_5)
        self.leafBorderSizeLabel.setMinimumSize(QtCore.QSize(120, 27))
        self.leafBorderSizeLabel.setMaximumSize(QtCore.QSize(120, 27))
        self.leafBorderSizeLabel.setObjectName("leafBorderSizeLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.leafBorderSizeLabel)
        self.leafSizeLineEdit = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leafSizeLineEdit.sizePolicy().hasHeightForWidth())
        self.leafSizeLineEdit.setSizePolicy(sizePolicy)
        self.leafSizeLineEdit.setMinimumSize(QtCore.QSize(90, 27))
        self.leafSizeLineEdit.setMaximumSize(QtCore.QSize(120, 27))
        self.leafSizeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.leafSizeLineEdit.setObjectName("leafSizeLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leafSizeLineEdit)
        self.leafBorderSizeLineEdit = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leafBorderSizeLineEdit.sizePolicy().hasHeightForWidth())
        self.leafBorderSizeLineEdit.setSizePolicy(sizePolicy)
        self.leafBorderSizeLineEdit.setMinimumSize(QtCore.QSize(90, 27))
        self.leafBorderSizeLineEdit.setMaximumSize(QtCore.QSize(120, 27))
        self.leafBorderSizeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.leafBorderSizeLineEdit.setObjectName("leafBorderSizeLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leafBorderSizeLineEdit)
        self.gridLayout_2.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lesionSizeLabel = QtWidgets.QLabel(self.frame_6)
        self.lesionSizeLabel.setMinimumSize(QtCore.QSize(130, 27))
        self.lesionSizeLabel.setMaximumSize(QtCore.QSize(150, 27))
        self.lesionSizeLabel.setObjectName("lesionSizeLabel")
        self.gridLayout_14.addWidget(self.lesionSizeLabel, 0, 0, 1, 1)
        self.lesionSizeLineEdit = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lesionSizeLineEdit.sizePolicy().hasHeightForWidth())
        self.lesionSizeLineEdit.setSizePolicy(sizePolicy)
        self.lesionSizeLineEdit.setMinimumSize(QtCore.QSize(90, 27))
        self.lesionSizeLineEdit.setMaximumSize(QtCore.QSize(120, 27))
        self.lesionSizeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lesionSizeLineEdit.setObjectName("lesionSizeLineEdit")
        self.gridLayout_14.addWidget(self.lesionSizeLineEdit, 0, 1, 1, 1)
        self.lesionBorderLabel = QtWidgets.QLabel(self.frame_6)
        self.lesionBorderLabel.setMinimumSize(QtCore.QSize(130, 27))
        self.lesionBorderLabel.setMaximumSize(QtCore.QSize(150, 27))
        self.lesionBorderLabel.setObjectName("lesionBorderLabel")
        self.gridLayout_14.addWidget(self.lesionBorderLabel, 1, 0, 1, 1)
        self.lesionBorderLineEdit = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lesionBorderLineEdit.sizePolicy().hasHeightForWidth())
        self.lesionBorderLineEdit.setSizePolicy(sizePolicy)
        self.lesionBorderLineEdit.setMinimumSize(QtCore.QSize(90, 27))
        self.lesionBorderLineEdit.setMaximumSize(QtCore.QSize(120, 27))
        self.lesionBorderLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lesionBorderLineEdit.setObjectName("lesionBorderLineEdit")
        self.gridLayout_14.addWidget(self.lesionBorderLineEdit, 1, 1, 1, 1)
        self.lesioncolorLabel = QtWidgets.QLabel(self.frame_6)
        self.lesioncolorLabel.setMinimumSize(QtCore.QSize(130, 27))
        self.lesioncolorLabel.setMaximumSize(QtCore.QSize(150, 27))
        self.lesioncolorLabel.setObjectName("lesioncolorLabel")
        self.gridLayout_14.addWidget(self.lesioncolorLabel, 2, 0, 1, 1)
        self.lesionColorComboBox = QtWidgets.QComboBox(self.frame_6)
        self.lesionColorComboBox.setObjectName("lesionColorComboBox")
        self.lesionColorComboBox.addItem("")
        self.lesionColorComboBox.addItem("")
        self.gridLayout_14.addWidget(self.lesionColorComboBox, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_6, 4, 1, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.CalibrationFileLabel = QtWidgets.QLabel(self.frame_7)
        self.CalibrationFileLabel.setMinimumSize(QtCore.QSize(150, 27))
        self.CalibrationFileLabel.setMaximumSize(QtCore.QSize(150, 27))
        self.CalibrationFileLabel.setObjectName("CalibrationFileLabel")
        self.gridLayout_15.addWidget(self.CalibrationFileLabel, 0, 0, 1, 1)
        self.loadCalibrationFilePushButton = QtWidgets.QPushButton(self.frame_7)
        self.loadCalibrationFilePushButton.setMinimumSize(QtCore.QSize(119, 27))
        self.loadCalibrationFilePushButton.setMaximumSize(QtCore.QSize(119, 27))
        self.loadCalibrationFilePushButton.setObjectName("loadCalibrationFilePushButton")
        self.gridLayout_15.addWidget(self.loadCalibrationFilePushButton, 0, 1, 1, 1)
        self.CalibrationFileOpenLineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.CalibrationFileOpenLineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.CalibrationFileOpenLineEdit.setMaximumSize(QtCore.QSize(500, 27))
        self.CalibrationFileOpenLineEdit.setText("")
        self.CalibrationFileOpenLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.CalibrationFileOpenLineEdit.setObjectName("CalibrationFileOpenLineEdit")
        self.gridLayout_15.addWidget(self.CalibrationFileOpenLineEdit, 0, 2, 1, 1)
        self.pathOutLabel = QtWidgets.QLabel(self.frame_7)
        self.pathOutLabel.setMinimumSize(QtCore.QSize(150, 27))
        self.pathOutLabel.setMaximumSize(QtCore.QSize(150, 27))
        self.pathOutLabel.setObjectName("pathOutLabel")
        self.gridLayout_15.addWidget(self.pathOutLabel, 2, 0, 1, 1)
        self.loadPathOutPushButton = QtWidgets.QPushButton(self.frame_7)
        self.loadPathOutPushButton.setMinimumSize(QtCore.QSize(119, 27))
        self.loadPathOutPushButton.setMaximumSize(QtCore.QSize(119, 27))
        self.loadPathOutPushButton.setObjectName("loadPathOutPushButton")
        self.gridLayout_15.addWidget(self.loadPathOutPushButton, 2, 1, 1, 1)
        self.pathOutlineEdit = QtWidgets.QLineEdit(self.frame_7)
        self.pathOutlineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.pathOutlineEdit.setMaximumSize(QtCore.QSize(500, 27))
        self.pathOutlineEdit.setText("")
        self.pathOutlineEdit.setObjectName("pathOutlineEdit")
        self.gridLayout_15.addWidget(self.pathOutlineEdit, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_7, 2, 0, 1, 2)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.pathInLabel = QtWidgets.QLabel(self.frame_8)
        self.pathInLabel.setMinimumSize(QtCore.QSize(150, 27))
        self.pathInLabel.setMaximumSize(QtCore.QSize(150, 27))
        self.pathInLabel.setObjectName("pathInLabel")
        self.gridLayout_16.addWidget(self.pathInLabel, 0, 0, 1, 1)
        self.loadAnalysisPushButton = QtWidgets.QPushButton(self.frame_8)
        self.loadAnalysisPushButton.setMinimumSize(QtCore.QSize(119, 27))
        self.loadAnalysisPushButton.setMaximumSize(QtCore.QSize(119, 27))
        self.loadAnalysisPushButton.setObjectName("loadAnalysisPushButton")
        self.gridLayout_16.addWidget(self.loadAnalysisPushButton, 0, 1, 1, 1)
        self.analysisOpenLineEdit = QtWidgets.QLineEdit(self.frame_8)
        self.analysisOpenLineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.analysisOpenLineEdit.setMaximumSize(QtCore.QSize(500, 27))
        self.analysisOpenLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.analysisOpenLineEdit.setText("")
        self.analysisOpenLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.analysisOpenLineEdit.setObjectName("analysisOpenLineEdit")
        self.gridLayout_16.addWidget(self.analysisOpenLineEdit, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_8, 1, 0, 1, 2)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tabAnalysis)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.runAnalysisPushButton = QtWidgets.QPushButton(self.frame_4)
        self.runAnalysisPushButton.setMinimumSize(QtCore.QSize(0, 27))
        self.runAnalysisPushButton.setMaximumSize(QtCore.QSize(700, 27))
        self.runAnalysisPushButton.setObjectName("runAnalysisPushButton")
        self.gridLayout_13.addWidget(self.runAnalysisPushButton, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_4, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabAnalysis, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.displayErrorEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.displayErrorEdit.setMaximumSize(QtCore.QSize(900, 50))
        self.displayErrorEdit.setObjectName("displayErrorEdit")
        self.verticalLayout.addWidget(self.displayErrorEdit)
        GUI_EBimage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GUI_EBimage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 25))
        self.menubar.setObjectName("menubar")
        GUI_EBimage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GUI_EBimage)
        self.statusbar.setObjectName("statusbar")
        GUI_EBimage.setStatusBar(self.statusbar)

        self.retranslateUi(GUI_EBimage)
        self.tabWidget.setCurrentIndex(1)
        self.futherCategoriesComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GUI_EBimage)

    def retranslateUi(self, GUI_EBimage):
        _translate = QtCore.QCoreApplication.translate
        GUI_EBimage.setWindowTitle(_translate("GUI_EBimage", "MainWindow"))
        self.writeLabel.setText(_translate("GUI_EBimage", "<html><head/><body><p align=\"center\">written by BONNOT François,  ALI Sajid, RAVEL Sébastien, FOURNIER Elisabeth</p></body></html>"))
        self.welcomeLabel.setText(_translate("GUI_EBimage", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Welcome Images Analysis Program V1</span></p></body></html>"))
        self.resetCalibrationPushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>run the programm</p></body></html>"))
        self.resetCalibrationPushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>run the programm</p></body></html>"))
        self.resetCalibrationPushButton.setText(_translate("GUI_EBimage", "Reset"))
        self.runCalibrationPushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>run the programm</p></body></html>"))
        self.runCalibrationPushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>run the programm</p></body></html>"))
        self.runCalibrationPushButton.setText(_translate("GUI_EBimage", "Run"))
        self.inputSetLabel.setText(_translate("GUI_EBimage", "<html><head/><body><p><span style=\" font-weight:600;\">Calibration input directories:</span></p></body></html>"))
        self.loadSymptomPushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadSymptomPushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadSymptomPushButton.setText(_translate("GUI_EBimage", "Load directory"))
        self.loadLeafPushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadLeafPushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadLeafPushButton.setText(_translate("GUI_EBimage", "Load directory"))
        self.symptomLabel.setText(_translate("GUI_EBimage", "Symptom folder"))
        self.symptomOpenLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.leafOpenLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.leafLabel.setText(_translate("GUI_EBimage", "Leaf folder"))
        self.backgroundLabel.setText(_translate("GUI_EBimage", "Background folder"))
        self.loadBackgroundPushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadBackgroundPushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadBackgroundPushButton.setText(_translate("GUI_EBimage", "Load directory"))
        self.backgroundOpenLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.category1LabelLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.category1LabelLineEdit.setText(_translate("GUI_EBimage", "Cat1Label"))
        self.category1OpenLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.loadCategory1PushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadCategory1PushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadCategory1PushButton.setText(_translate("GUI_EBimage", "Load directory"))
        self.loadCategoryPushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadCategoryPushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadCategoryPushButton.setText(_translate("GUI_EBimage", "Load directory"))
        self.category2LabelLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.category2LabelLineEdit.setText(_translate("GUI_EBimage", "Cat2Label"))
        self.category2OpenLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.futherCatLabel.setText(_translate("GUI_EBimage", "Further categories (optional) "))
        self.futherCategoriesComboBox.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Modifie the graph build by R script. See below to select value<br/></p></body></html>"))
        self.futherCategoriesComboBox.setItemText(0, _translate("GUI_EBimage", "0"))
        self.futherCategoriesComboBox.setItemText(1, _translate("GUI_EBimage", "1"))
        self.futherCategoriesComboBox.setItemText(2, _translate("GUI_EBimage", "2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCalibration), _translate("GUI_EBimage", "Calibration"))
        self.imgLabel.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Graphic previous<br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GUI_EBimage", "Page"))
        self.analysisLabel.setText(_translate("GUI_EBimage", "<html><head/><body><p><span style=\" font-weight:600;\">Analysis directories:</span></p></body></html>"))
        self.leafSizeLabel.setText(_translate("GUI_EBimage", "Leaf Min Size"))
        self.leafBorderSizeLabel.setText(_translate("GUI_EBimage", "Leaf Border Size"))
        self.leafSizeLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.leafSizeLineEdit.setText(_translate("GUI_EBimage", "1000"))
        self.leafBorderSizeLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.leafBorderSizeLineEdit.setText(_translate("GUI_EBimage", "3"))
        self.lesionSizeLabel.setText(_translate("GUI_EBimage", "Lesion Min Size"))
        self.lesionSizeLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.lesionSizeLineEdit.setText(_translate("GUI_EBimage", "10"))
        self.lesionBorderLabel.setText(_translate("GUI_EBimage", "Lesion Border Size"))
        self.lesionBorderLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.lesionBorderLineEdit.setText(_translate("GUI_EBimage", "3"))
        self.lesioncolorLabel.setText(_translate("GUI_EBimage", "Lesion color output"))
        self.lesionColorComboBox.setItemText(0, _translate("GUI_EBimage", "Black"))
        self.lesionColorComboBox.setItemText(1, _translate("GUI_EBimage", "White"))
        self.CalibrationFileLabel.setText(_translate("GUI_EBimage", "Calibration file"))
        self.loadCalibrationFilePushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadCalibrationFilePushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadCalibrationFilePushButton.setText(_translate("GUI_EBimage", "Load directory"))
        self.CalibrationFileOpenLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.pathOutLabel.setText(_translate("GUI_EBimage", "Path Output files"))
        self.loadPathOutPushButton.setText(_translate("GUI_EBimage", "Load directory"))
        self.pathOutlineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Path to output file, </p><p>by default in the same path as programme</p></body></html>"))
        self.pathOutlineEdit.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>Path to output file, </p><p>by default in the same path as programme</p></body></html>"))
        self.pathInLabel.setText(_translate("GUI_EBimage", "Input:"))
        self.loadAnalysisPushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadAnalysisPushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>Open file dialog to load list accession file (.txt)</p></body></html>"))
        self.loadAnalysisPushButton.setText(_translate("GUI_EBimage", "Load directory"))
        self.analysisOpenLineEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>\n"
"Number of population maximum for DAPC. (Warning: R script colours contain only 10 values increase numbre if you select more than 10.)<br/>\n"
"An optinal integer indicating the number of clusters to be sought.<br/>\n"
"If provided, the function will only run K-means once, for this number of clusters.<br/>\n"
"If left as NULL, several K-means are run for a range of k (number of clusters) values.</p></body></html>"))
        self.runAnalysisPushButton.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p>run the programm</p></body></html>"))
        self.runAnalysisPushButton.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>run the programm</p></body></html>"))
        self.runAnalysisPushButton.setText(_translate("GUI_EBimage", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnalysis), _translate("GUI_EBimage", "Analyses"))
        self.displayErrorEdit.setToolTip(_translate("GUI_EBimage", "<html><head/><body><p><br/></p></body></html>"))
        self.displayErrorEdit.setWhatsThis(_translate("GUI_EBimage", "<html><head/><body><p>error display</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI_EBimage = QtWidgets.QMainWindow()
    ui = Ui_GUI_EBimage()
    ui.setupUi(GUI_EBimage)
    GUI_EBimage.show()
    sys.exit(app.exec_())

